name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if endpoint_url secret exists"
        env:
          endpoint_url: ${{ secrets.ENDPOINT_URL }}
        if: ${{ env.endpoint_url == '' }}
        run: 'echo "::error:: The variable \"ENDPOINT_URL\" is empty" && exit 1'

      - name: "Check if bucket_name secret exists"
        env:
          bucket_name: ${{ secrets.BUCKET_NAME }}
        if: ${{ env.bucket_name == '' }}
        run: 'echo "::error:: The variable \"BUCKET_NAME\" is empty" && exit 1'

      - name: "Check if aws_access_key_id secret exists"
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        if: ${{ env.aws_access_key_id == '' }}
        run: 'echo "::error:: The variable \"AWS_ACCESS_KEY_ID\" is empty" && exit 1'

      - name: "Check if aws_secret_access_key secret exists"
        env:
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ env.aws_secret_access_key == '' }}
        run: 'echo "::error:: The variable \"AWS_SECRET_ACCESS_KEY\" is empty" && exit 1'
  release:
    needs: check-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requriments
        run: |
          npm i @diplodoc/cli -g
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Build
        run: |
          rm -rf docs-html; yfm -i ./ -o ./docs-html

      - name: Release
        run: |
          echo ${ENDPOINT_URL}
          aws --endpoint-url=${ENDPOINT_URL} s3 sync . s3://${BUCKET_NAME}
